### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by mady143** [sahil280114/tflite_example#1]
Hi @sahil280114 ,
 I had successfully implemented the tflite package in flutter but at last we are getting the output in that we are getting like {{confidence:0.78326,index:1,label:name}} i want to display the only label with specific font and style can you explain how can i get that 

Thanks and Regards,
Manikantha Sekhar.

**Comment by sahil280114** [comment]
Hey!
You can try this-
`var outputString = output.toString().replaceAll("[{", "").replaceAll("}]", "")
                       .replaceAll("label", "LABEL").replaceAll("confidence", "CONFIDENCE");`

**Comment by mmusunur** [comment]
Hi I actually modified my code with your code which you have sent to but
it’s just replacing with new one but I want to remove the confidence and
index only I have to display the label it’s self

**Comment by mmusunur** [comment]
I resolved it

**Comment by mmusunur** [comment]
I resolved the issue by replacing the label.txt file with another file though its working fine and i am display the output without the error please find the bellow attachement

![finallll](https://user-images.githubusercontent.com/37180858/87269857-18770280-c4ec-11ea-82b9-56f4795117be.png)



but i want to know that i want to get the model from serve and also i tried to import my model in Firebase ML server but its showing the file could not exceeds with 100 mb but my tflite model is more that 100mb could you explain me how to resolve and i want to get the model access from server.

Thanks and Regards,
Manikantha Sekhar..

**Comment by mmusunur** [comment]
Hi @sahil280114 

I want to know some information regarding my app just i have created an app in flutter and i deployed a ml model into that app locally and working fine while taking the build its of more than 40 mb size in that my model is of 42mb size so its taking to large so i want to do i want to call my model from the server i was completed don't about that functionality could you help me in that .

Thanks & Regards,
Manikantha Sekhar.
